FROM node:26

WORKDIR /app

RUN mkdir -p /app/node_modules /app/.npm-cache /app/static/js /app/static/css /app/static/img /app/static/webfonts && \
    chown -R node:node /app

COPY --chown=node:node package*.json tsconfig.json ./
COPY --chown=node:node vite.config.ts ./

# USER node

# Configurer npm localement et installer les dépendances
RUN npm config set cache /app/.npm-cache && \
    npm install --ignore-scripts

# Compiler pour produire les assets
CMD ["npm", "run", "build"]