#!/bin/bash

# Script de démonstration SonarQube
# Analyse les fichiers créés pour la démo

echo "================================================"
echo "  Démonstration SonarQube - AmbianceBoard"
echo "================================================"
echo ""

echo "📊 Fichiers de démonstration créés :"
echo ""

echo "Python (Backend) :"
echo "  ✓ security_vulnerabilities.py   - Failles de sécurité (20+)"
echo "  ✓ code_duplication_1.py         - Code dupliqué (partie 1)"
echo "  ✓ code_duplication_2.py         - Code dupliqué (partie 2)"
echo "  ✓ high_complexity.py            - Complexité élevée (>150)"
echo "  ✓ code_smells.py                - Code smells & TODOs (32+)"
echo "  ✓ bugs_and_errors.py            - Bugs potentiels (40+)"
echo "  ✓ performance_issues.py         - Problèmes de performance (25+)"
echo "  ✓ mixed_issues.py               - Problèmes variés (40+)"
echo "  ✓ legacy_issues.py              - Dette technique (35+)"
echo ""

echo "TypeScript/JavaScript (Frontend) :"
echo "  ✓ demo_sonar_issues.ts          - Problèmes JS/TS (45+)"
echo "  ✓ more_sonar_issues.ts          - Plus de problèmes JS (35+)"
echo ""

echo "================================================"
echo "  Résumé des Problèmes Attendus"
echo "================================================"
echo ""
echo "🔴 Bugs                    : 80+"
echo "🟠 Vulnerabilities         : 50+ (Critical/High)"
echo "🟡 Code Smells             : 150+"
echo "🔵 Security Hotspots       : 30+"
echo "📊 Duplication             : 15-20%"
echo "⚡ Complexité              : Plusieurs >50"
echo "💰 Dette Technique         : Plusieurs jours"
echo "📝 TODOs/FIXMEs            : 60+"
echo ""

echo "================================================"
echo "  Types de Problèmes Inclus"
echo "================================================"
echo ""
echo "Sécurité :"
echo "  • SQL Injection"
echo "  • Command Injection"
echo "  • XSS (Cross-Site Scripting)"
echo "  • Hardcoded Credentials"
echo "  • Weak Cryptography (MD5)"
echo "  • eval()/exec() usage"
echo "  • Unsafe Deserialization (Pickle, YAML)"
echo "  • XXE Vulnerability"
echo "  • Path Traversal"
echo "  • LDAP Injection"
echo "  • SSL Verification Disabled"
echo "  • ReDoS (Regular Expression DoS)"
echo ""

echo "Qualité du Code :"
echo "  • Complexité Cyclomatique Élevée"
echo "  • Duplication de Code"
echo "  • Fonctions trop longues"
echo "  • Trop de paramètres"
echo "  • God Classes"
echo "  • Magic Numbers"
echo "  • Code Mort (Dead Code)"
echo "  • Variables Inutilisées"
echo "  • TODOs/FIXMEs non résolus"
echo ""

echo "Bugs Potentiels :"
echo "  • Division par zéro"
echo "  • Null Pointer Exceptions"
echo "  • Index Out of Range"
echo "  • Boucles Infinies"
echo "  • Race Conditions"
echo "  • Memory Leaks"
echo "  • Exception Handling incorrect"
echo ""

echo "Performance :"
echo "  • Algorithmes O(n²)"
echo "  • N+1 Queries"
echo "  • Pas de Cache"
echo "  • Import dans boucles"
echo "  • String concatenation inefficace"
echo ""

echo "================================================"
echo "  Commandes pour l'Analyse"
echo "================================================"
echo ""
echo "Si vous avez SonarQube installé localement :"
echo ""
echo "  # Avec sonar-scanner"
echo "  sonar-scanner \\"
echo "    -Dsonar.projectKey=AmbianceBoard-Demo \\"
echo "    -Dsonar.sources=app/main/application,frontend/src \\"
echo "    -Dsonar.host.url=http://localhost:9000 \\"
echo "    -Dsonar.login=YOUR_TOKEN"
echo ""
echo "  # Avec Maven (si applicable)"
echo "  mvn sonar:sonar"
echo ""
echo "  # Avec Gradle (si applicable)"
echo "  gradle sonarqube"
echo ""

echo "================================================"
echo "  Points Clés pour la Présentation"
echo "================================================"
echo ""
echo "1. Dashboard Overview"
echo "   → Montrer les métriques globales"
echo ""
echo "2. Security Vulnerabilities"
echo "   → SQL Injection, Hardcoded Secrets, etc."
echo ""
echo "3. Code Smells"
echo "   → Complexité, Duplication, TODOs"
echo ""
echo "4. Bugs Détectés"
echo "   → Division par zéro, Null pointers"
echo ""
echo "5. Technical Debt"
echo "   → Temps estimé pour corriger"
echo ""
echo "6. Code Coverage (si tests)"
echo "   → Pourcentage de couverture"
echo ""
echo "7. Duplications"
echo "   → Visualisation des blocs dupliqués"
echo ""
echo "8. Complexity"
echo "   → Fonctions avec complexité >15"
echo ""

echo "================================================"
echo "  ⚠️  AVERTISSEMENT"
echo "================================================"
echo ""
echo "Ce code contient VOLONTAIREMENT des problèmes"
echo "de sécurité et de qualité pour la démonstration."
echo ""
echo "NE JAMAIS utiliser ce code en production !"
echo "NE PAS copier ces patterns dans vos projets !"
echo ""
echo "================================================"
echo ""

echo "✅ Prêt pour la démonstration SonarQube !"
echo ""
