services:
  cronjob:
    build: ./app
    command: cron -f
    volumes:
      - ./mediafiles:/usr/src/app/mediafiles/
    env_file:
      - ./.env
    environment:
      - RUNCRON=1
    depends_on:
      - db
      - rabbitmq  # Ajout de la dépendance à RabbitMQ

  back:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn parameters.wsgi:application --bind 0.0.0.0:${WEB_PORT} --workers=3
    volumes:
      - ./staticfiles:/usr/src/app/static/
      - ./mediafiles:/usr/src/app/mediafiles/
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - ./.env
    environment:
      - RUNCRON=0
    depends_on:
      - db
      - rabbitmq
      - front

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run build
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./staticfiles:/app/static
    environment:
      - DEBUG=0
      


  db:
    image: postgres:15.8
    ports:
      - $SQL_PORT:$SQL_PORT
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management  # Version avec interface de gestion
    ports:
      - ${RABBIT_MQ_PORT_AMQP}:${RABBIT_MQ_PORT_AMQP}    # Port pour AMQP
      - ${RABBIT_MQ_PORT_WEB}:${RABBIT_MQ_PORT_WEB}  # Port pour l'interface web de gestion
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}     # Utilisateur par défaut
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}      # Mot de passe par défaut
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq # Persistance des données

volumes:
  db-data: null
  rabbitmq-data: null
