sonar.projectKey=AmbianceBoard
sonar.projectName=chaBiselx_AmbianceBoard
sonar.organization=chabiselx


# Exclure le dossier app/main/migrations des analyses
sonar.exclusions[0]=app/main/migrations/**
sonar.exclusions[1]=app/main/TNR/**
sonar.exclusions[2]=app/frontend/tests/**
sonar.exclusions[3]=music-labeler/tests/**