sonar.projectKey=chaBiselx_AmbianceBoard
sonar.projectName=AmbianceBoard
sonar.organization=chabiselx


# Exclure les dossiers de tests et migrations des analyses
sonar.exclusions=app/main/migrations/**,app/main/TNR/**,app/frontend/tests/**,music-labeler/tests/**