# Generated by Django 5.1.6 on 2025-07-31 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message de la notification en HTML')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de début d'affichage de la notification")),
                ('end_date', models.DateTimeField(help_text="Date et heure de fin d'affichage de la notification")),
                ('for_authenticated_users', models.BooleanField(default=True, help_text='Si True, la notification est réservée aux utilisateurs connectés. Si False, pour tous les utilisateurs.')),
                ('is_active', models.BooleanField(default=True, help_text='Permet de désactiver temporairement la notification sans la supprimer')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la notification')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Notification générale',
                'verbose_name_plural': 'Notifications générales',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='main_genera_start_d_15cc87_idx'), models.Index(fields=['is_active'], name='main_genera_is_acti_fa5944_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de fermeture de la notification')),
                ('notification', models.ForeignKey(help_text='Notification qui a été fermée', on_delete=django.db.models.deletion.CASCADE, to='main.generalnotification')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a fermé la notification', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fermeture de notification',
                'verbose_name_plural': 'Fermetures de notifications',
                'indexes': [models.Index(fields=['user', 'notification'], name='main_userno_user_id_f11d13_idx'), models.Index(fields=['dismissed_at'], name='main_userno_dismiss_97fabf_idx')],
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
