# Generated by Django 5.1.6 on 2025-07-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_generalnotification_usernotificationdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnotification',
            name='class_name',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', help_text='Classe CSS pour le style de la notification', max_length=64),
        ),
    ]
