# Generated by Django 5.1.6 on 2025-08-01 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_generalnotification_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnotification',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique de la notification', unique=True),
        ),
    ]
