# Generated by Django 5.1.6 on 2025-08-19 11:52

import main.domain.common.utils.OverwriteStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_generalnotification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, storage=main.domain.common.utils.OverwriteStorage.OverwriteStorage(), upload_to='playlistIcon/'),
        ),
        migrations.AlterField(
            model_name='soundboard',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, storage=main.domain.common.utils.OverwriteStorage.OverwriteStorage(), upload_to='soundBoardIcon/'),
        ),
    ]
