# Generated by Django 5.1.6 on 2025-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_useractivity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'LOGIN'), ('logout', 'LOGOUT'), ('registration', 'REGISTRATION'), ('soundboard_create', 'SOUNDBOARD_CREATE'), ('soundboard_view', 'SOUNDBOARD_VIEW'), ('soundboard_share', 'SOUNDBOARD_SHARE'), ('playlist_create', 'PLAYLIST_CREATE'), ('playlist_view', 'PLAYLIST_VIEW'), ('music_upload', 'MUSIC_UPLOAD'), ('music_delete', 'MUSIC_DELETE'), ('report_content', 'REPORT_CONTENT'), ('error_404', 'ERROR_404'), ('error_500', 'ERROR_500'), ('error_permission', 'ERROR_PERMISSION')], db_index=True, help_text="Type d'activité effectuée par l'utilisateur", max_length=64),
        ),
    ]
