# Generated by Django 5.1.6 on 2025-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_useractivity_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'LOGIN'), ('logout', 'LOGOUT'), ('registration', 'REGISTRATION'), ('soundboard_create', 'SOUNDBOARD_CREATE'), ('soundboard_view', 'SOUNDBOARD_VIEW'), ('soundboard_share', 'SOUNDBOARD_SHARE'), ('soundboard_delete', 'SOUNDBOARD_DELETE'), ('playlist_create', 'PLAYLIST_CREATE'), ('playlist_view', 'PLAYLIST_VIEW'), ('playlist_delete', 'PLAYLIST_DELETE'), ('music_upload', 'MUSIC_UPLOAD'), ('music_delete', 'MUSIC_DELETE'), ('link_upload', 'LINK_UPLOAD'), ('link_delete', 'LINK_DELETE'), ('report_content', 'REPORT_CONTENT'), ('error_404', 'ERROR_404'), ('error_500', 'ERROR_500'), ('error_permission', 'ERROR_PERMISSION')], db_index=True, help_text="Type d'activité effectuée par l'utilisateur", max_length=64),
        ),
    ]
