# Generated by Django 5.1.6 on 2025-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_useractivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'LOGIN'), ('logout', 'LOGOUT'), ('registration', 'REGISTRATION'), ('soundboard_create', 'SOUNDBOARD_CREATE'), ('soundboard_view', 'SOUNDBOARD_VIEW'), ('soundboard_share', 'SOUNDBOARD_SHARE'), ('soundboard_delete', 'SOUNDBOARD_DELETE'), ('playlist_create', 'PLAYLIST_CREATE'), ('playlist_delete', 'PLAYLIST_DELETE'), ('music_upload', 'MUSIC_UPLOAD'), ('music_delete', 'MUSIC_DELETE'), ('link_upload', 'LINK_UPLOAD'), ('link_delete', 'LINK_DELETE'), ('report_content', 'REPORT_CONTENT'), ('error_404', 'ERROR_404'), ('error_405', 'ERROR_405'), ('error_406', 'ERROR_406'), ('error_429', 'ERROR_429'), ('error_4xx', 'ERROR_4XX'), ('error_500', 'ERROR_500'), ('error_5xx', 'ERROR_5XX')], db_index=True, help_text="Type d'activité effectuée par l'utilisateur", max_length=64),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Clé de session pour identifier les utilisateurs non connectés', max_length=40),
        ),
    ]
