# Generated by Django 5.1.6 on 2025-10-02 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_useractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='playlistDim',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='soundboardDim',
        ),
        migrations.CreateModel(
            name='UserDevicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'MOBILE'), ('tablet', 'TABLET'), ('desktop', 'DESKTOP')], max_length=50, verbose_name="Type d'appareil")),
                ('playlist_dim', models.IntegerField(blank=True, help_text="Si défini, remplace la dimension par défaut pour ce type d'appareil", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Dimension playlist spécifique')),
                ('soundboard_dim', models.IntegerField(blank=True, help_text="Si défini, remplace la dimension par défaut pour ce type d'appareil", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Dimension soundboard spécifique')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_preferences', to='main.userpreference')),
            ],
            options={
                'verbose_name': 'Préférence par appareil',
                'verbose_name_plural': 'Préférences par appareil',
                'unique_together': {('user_preference', 'device_type')},
            },
        ),
    ]
