# Generated by Django 5.1.6 on 2025-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_userpreference_playlistdim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboardplaylist',
            name='section',
            field=models.IntegerField(default=1),
        ),
    ]
