# Generated by Django 5.1.6 on 2025-10-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_soundboardplaylist_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboardplaylist',
            name='activable_by_player',
            field=models.BooleanField(default=False),
        ),
    ]
