# Generated by Django 5.1.6 on 2025-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_soundboardplaylist_activable_by_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
