# Generated by Django 5.1.6 on 2025-10-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fadeIn',
            field=models.CharField(choices=[('DEFAULT', 'Par défaut'), ('YES', 'Oui'), ('NO', 'Non')], default='DEFAULT', max_length=64),
        ),
        migrations.AddField(
            model_name='playlist',
            name='fadeOut',
            field=models.CharField(choices=[('DEFAULT', 'Par défaut'), ('YES', 'Oui'), ('NO', 'Non')], default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('REGISTRATION', 'registration'), ('SOUNDBOARD_CREATE', 'soundboard_create'), ('SOUNDBOARD_VIEW', 'soundboard_view'), ('SOUNDBOARD_SHARE', 'soundboard_share'), ('SOUNDBOARD_DELETE', 'soundboard_delete'), ('PLAYLIST_CREATE', 'playlist_create'), ('PLAYLIST_DELETE', 'playlist_delete'), ('MUSIC_UPLOAD', 'music_upload'), ('MUSIC_DELETE', 'music_delete'), ('LINK_UPLOAD', 'link_upload'), ('LINK_DELETE', 'link_delete'), ('REPORT_CONTENT', 'report_content'), ('ERROR_404', 'error_404'), ('ERROR_405', 'error_405'), ('ERROR_406', 'error_406'), ('ERROR_429', 'error_429'), ('ERROR_4XX', 'error_4xx'), ('ERROR_500', 'error_500'), ('ERROR_5XX', 'error_5xx')], db_index=True, help_text="Type d'activité effectuée par l'utilisateur", max_length=64),
        ),
    ]
