# Generated by Django 5.1.6 on 2025-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_playlist_fadein_playlist_fadeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboardplaylist',
            name='shortcut_keyboard',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
