# Generated by Django 5.1.6 on 2025-11-26 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_soundboardplaylist_shortcut_keyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_copiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generalnotification',
            name='class_name',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', help_text='Classe CSS pour le style de la notification', max_length=64, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='generalnotification',
            name='end_date',
            field=models.DateTimeField(help_text="Date et heure de fin d'affichage de la notification", verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='generalnotification',
            name='for_authenticated_users',
            field=models.BooleanField(default=True, help_text='Si True, la notification est réservée aux utilisateurs connectés. Si False, pour tous les utilisateurs.', verbose_name='Réservé aux utilisateurs connectés'),
        ),
        migrations.AlterField(
            model_name='generalnotification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Permet de désactiver temporairement la notification sans la supprimer', verbose_name='Notification active'),
        ),
        migrations.AlterField(
            model_name='generalnotification',
            name='message',
            field=models.TextField(help_text='Message de la notification en HTML', verbose_name='Message (HTML)'),
        ),
        migrations.AlterField(
            model_name='generalnotification',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de début d'affichage de la notification", verbose_name='Date de début'),
        ),
    ]
