# Generated by Django 5.1.6 on 2025-11-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_playlist_is_copiable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistDuplicationHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_playlist_name', models.CharField(help_text='Nom de la playlist source au moment de la duplication', max_length=255)),
                ('source_playlist_uuid', models.UUIDField(help_text='UUID de la playlist source')),
                ('duplicated_playlist', models.ForeignKey(help_text='La playlist dupliquée (copie)', on_delete=django.db.models.deletion.CASCADE, related_name='duplication_history', to='main.playlist')),
                ('source_playlist', models.ForeignKey(blank=True, help_text='La playlist originale qui a été dupliquée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplication_sources', to='main.playlist')),
            ],
            options={
                'verbose_name': 'Historique de duplication de playlist',
                'verbose_name_plural': 'Historiques de duplication de playlists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_playlist_uuid'], name='main_playli_source__44dcdf_idx')],
            },
        ),
    ]
