# Generated by Django 5.1.6 on 2025-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_playlistduplicationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='moderator_ban_copie',
            field=models.BooleanField(default=False),
        ),
    ]
