# Generated by Django 5.1 on 2026-05-18 11:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_playlist_moderator_ban_copie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(db_index=True, max_length=100)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='main.track')),
            ],
            options={
                'verbose_name': 'Track Label',
                'verbose_name_plural': 'Track Labels',
                'ordering': ['-confidence'],
                'indexes': [models.Index(fields=['track', '-confidence'], name='idx_tracklabel_track_conf'), models.Index(fields=['category', 'label'], name='idx_tracklabel_cat_label')],
                'unique_together': {('track', 'category', 'label')},
            },
        ),
    ]
