# Generated by Django 5.1.6 on 2026-06-05

from django.db import migrations, models


LEGACY_YES_MAPPING = {
    'PLAYLIST_TYPE_MUSIC': 'EASE',
    'PLAYLIST_TYPE_AMBIENT': 'EASE_IN',
    'PLAYLIST_TYPE_INSTANT': 'LINEAR',
}


def _map_legacy_yes(type_playlist: str) -> str:
    return LEGACY_YES_MAPPING.get(type_playlist, 'LINEAR')


def forwards_migrate_fade_values(apps, schema_editor):
    playlist_model = apps.get_model('main', 'Playlist')

    for playlist in playlist_model.objects.all().only('id', 'typePlaylist', 'fadeIn', 'fadeOut'):
        updated_fields = []

        if playlist.fadeIn == 'NO':
            playlist.fadeIn = 'disabled'
            updated_fields.append('fadeIn')
        elif playlist.fadeIn == 'YES':
            playlist.fadeIn = _map_legacy_yes(playlist.typePlaylist)
            updated_fields.append('fadeIn')

        if playlist.fadeOut == 'NO':
            playlist.fadeOut = 'disabled'
            updated_fields.append('fadeOut')
        elif playlist.fadeOut == 'YES':
            playlist.fadeOut = _map_legacy_yes(playlist.typePlaylist)
            updated_fields.append('fadeOut')

        if updated_fields:
            playlist.save(update_fields=updated_fields)


def backwards_migrate_fade_values(apps, schema_editor):
    # Migration irréversible sans perte d'information sur les courbes explicites.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_create_tracklabel'),
    ]

    operations = [
        migrations.RunPython(forwards_migrate_fade_values, backwards_migrate_fade_values),
        migrations.AlterField(
            model_name='playlist',
            name='fadeIn',
            field=models.CharField(
                choices=[
                    ('DEFAULT', 'Par défaut'),
                    ('DISABLED', 'Désactivé'),
                    ('LINEAR', 'linear'),
                    ('EASE', 'ease'),
                    ('EASE_IN', 'ease-in'),
                    ('EASE_OUT', 'ease-out'),
                    ('EASE_IN_QUAD', 'ease-in-quad'),
                    ('EASE_OUT_QUAD', 'ease-out-quad'),
                    ('EASE_IN_OUT_QUAD', 'ease-in-out-quad'),
                    ('EASE_OUT_CUBIC', 'ease-out-cubic'),
                ],
                default='DEFAULT',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='fadeOut',
            field=models.CharField(
                choices=[
                    ('DEFAULT', 'Par défaut'),
                    ('DISABLED', 'Désactivé'),
                    ('LINEAR', 'linear'),
                    ('EASE', 'ease'),
                    ('EASE_IN', 'ease-in'),
                    ('EASE_OUT', 'ease-out'),
                    ('EASE_IN_QUAD', 'ease-in-quad'),
                    ('EASE_OUT_QUAD', 'ease-out-quad'),
                    ('EASE_IN_OUT_QUAD', 'ease-in-out-quad'),
                    ('EASE_OUT_CUBIC', 'ease-out-cubic'),
                ],
                default='DEFAULT',
                max_length=64,
            ),
        ),
    ]
