# Generated by Django 5.1 on 2026-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_migrate_playlist_fade_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='fadeIn',
            field=models.CharField(choices=[('DEFAULT', 'enum.fade_playlist.default'), ('DISABLED', 'enum.fade_curve.disabled'), ('LINEAR', 'enum.fade_curve.linear'), ('EASE', 'enum.fade_curve.ease'), ('EASE_IN', 'enum.fade_curve.ease_in'), ('EASE_OUT', 'enum.fade_curve.ease_out'), ('EASE_IN_QUAD', 'enum.fade_curve.ease_in_quad'), ('EASE_OUT_QUAD', 'enum.fade_curve.ease_out_quad'), ('EASE_IN_OUT_QUAD', 'enum.fade_curve.ease_in_out_quad'), ('EASE_OUT_CUBIC', 'enum.fade_curve.ease_out_cubic')], default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='fadeOut',
            field=models.CharField(choices=[('DEFAULT', 'enum.fade_playlist.default'), ('DISABLED', 'enum.fade_curve.disabled'), ('LINEAR', 'enum.fade_curve.linear'), ('EASE', 'enum.fade_curve.ease'), ('EASE_IN', 'enum.fade_curve.ease_in'), ('EASE_OUT', 'enum.fade_curve.ease_out'), ('EASE_IN_QUAD', 'enum.fade_curve.ease_in_quad'), ('EASE_OUT_QUAD', 'enum.fade_curve.ease_out_quad'), ('EASE_IN_OUT_QUAD', 'enum.fade_curve.ease_in_out_quad'), ('EASE_OUT_CUBIC', 'enum.fade_curve.ease_out_cubic')], default='DEFAULT', max_length=64),
        ),
    ]
