# Generated by Django 5.1 on 2026-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_playlist_fadein_alter_playlist_fadeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboard',
            name='descriptionSEO',
            field=models.TextField(blank=True, default='', help_text='Description du soundboard'),
        ),
    ]
