# Generated by Django 5.1 on 2026-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_soundboard_descriptionseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='uri',
            field=models.URLField(blank=True, help_text="URI de la ressource ou de l'action effectuée", max_length=2000),
        ),
    ]
