# Generated by Django 5.1 on 2026-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_useractivity_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='uri',
            field=models.URLField(blank=True, default='', help_text="URI de la ressource ou de l'action effectuée", max_length=2000, null=True),
        ),
    ]
