# Generated by Django 5.2.15 on 2026-07-02 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_useractivity_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDemoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Identifiant unique de l'élément de démo", unique=True)),
                ('title', models.CharField(help_text='Texte principal affiché sur la carte', max_length=120, verbose_name='Titre')),
                ('icon', models.CharField(help_text="Emoji ou petit texte d'icône (ex: ⚔️, 🌌)", max_length=8, verbose_name='Icône')),
                ('state_text', models.CharField(default='Cliquer pour jouer', help_text='Texte secondaire affiché sous le titre', max_length=120, verbose_name="Texte d'état")),
                ('aria_label', models.CharField(blank=True, default='', help_text='Label aria personnalisé. Si vide, un label est généré automatiquement', max_length=255, verbose_name='Label accessibilité')),
                ('is_active', models.BooleanField(default=True, help_text="Permet d'activer ou désactiver l'élément sans le supprimer", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soundboard', models.ForeignKey(help_text="Soundboard public ciblé par l'élément", limit_choices_to={'is_public': True}, on_delete=django.db.models.deletion.CASCADE, related_name='home_demo_items', to='main.soundboard', verbose_name='Soundboard public')),
            ],
            options={
                'verbose_name': 'Élément de démo accueil',
                'verbose_name_plural': 'Éléments de démo accueil',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='main_homede_is_acti_490e44_idx')],
            },
        ),
    ]
