# Generated by Django 5.2.16 on 2026-07-08 19:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_homedemoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(db_index=True, help_text='Unique label without spaces used in URLs and filters', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Playlist tag name (3-50 characters)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Optional playlist tag description', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this playlist tag can be used for filtering')),
            ],
            options={
                'verbose_name': 'Playlist Tag',
                'verbose_name_plural': 'Playlist Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags dedies aux playlists', related_name='playlists', to='main.playlisttag'),
        ),
    ]
