# Generated by Django 5.2.16 on 2026-07-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_playlisttag_playlist_playlist_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='SoundboardTag',
        ),
        migrations.AlterModelOptions(
            name='soundboardtag',
            options={'ordering': ['name'], 'verbose_name': 'soundboard Tag', 'verbose_name_plural': 'soundboard Tags'},
        ),
        migrations.AlterModelTable(
            name='soundboardtag',
            table='main_soundboardtag',
        ),
    ]
