# Generated by Django 5.2.16 on 2026-07-17 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_tag_soundboardtag_alter_soundboardtag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncDownloadJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(db_index=True, default='youtube', max_length=50)),
                ('alternative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DOWNLOADING', 'DOWNLOADING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_download_jobs', to='main.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Async Download Job',
                'verbose_name_plural': 'Async Download Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['playlist', 'status'], name='idx_ytdljob_playlist_status'), models.Index(fields=['user', 'status'], name='idx_ytdljob_user_status')],
            },
        ),
    ]
