# Generated by Django 5.2.16 on 2026-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_asyncdownloadjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncdownloadjob',
            name='alternative_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asyncdownloadjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asyncdownloadjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
