# Generated by Django 6.0.7 on 2026-08-07 06:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_asyncdownloadjob_alternative_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAttributionVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('uri', models.URLField(blank=True, default='', max_length=2000)),
                ('referer_url', models.URLField(blank=True, default='', max_length=2000)),
                ('referer_domain', models.CharField(blank=True, db_index=True, default='direct', max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('utm_data', models.JSONField(blank=True, default=dict)),
                ('utm_source', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur associe a la visite si connecte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visite avec attribution',
                'verbose_name_plural': 'Visites avec attribution',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='main_traffi_visited_2d26ed_idx'), models.Index(fields=['referer_domain', 'visited_at'], name='main_traffi_referer_31bde8_idx'), models.Index(fields=['utm_source', 'visited_at'], name='main_traffi_utm_sou_1d30ae_idx')],
            },
        ),
    ]
