# Generated by Django 6.0.7 on 2026-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_trafficattributionvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboardtag',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indique si le tag est un tag par défaut'),
        ),
    ]
