# Generated by Django 6.0.7 on 2026-08-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_soundboardtag_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='fadeIn',
            field=models.CharField(choices=[('DEFAULT', 'enum.fade_playlist.default'), ('DISABLED', 'enum.fade_curve.disabled'), ('LINEAR', 'enum.fade_curve.linear'), ('EASE', 'enum.fade_curve.ease'), ('EASE_IN', 'enum.fade_curve.ease_in'), ('EASE_OUT', 'enum.fade_curve.ease_out'), ('EASE_IN_QUAD', 'enum.fade_curve.ease_in_quad'), ('EASE_OUT_QUAD', 'enum.fade_curve.ease_out_quad'), ('EASE_IN_OUT_QUAD', 'enum.fade_curve.ease_in_out_quad'), ('EASE_OUT_CUBIC', 'enum.fade_curve.ease_out_cubic'), ('EASE_IN_EXPONENTIAL', 'enum.fade_curve.ease_in_exponential'), ('EASE_OUT_EXPONENTIAL', 'enum.fade_curve.ease_out_exponential')], default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='fadeOut',
            field=models.CharField(choices=[('DEFAULT', 'enum.fade_playlist.default'), ('DISABLED', 'enum.fade_curve.disabled'), ('LINEAR', 'enum.fade_curve.linear'), ('EASE', 'enum.fade_curve.ease'), ('EASE_IN', 'enum.fade_curve.ease_in'), ('EASE_OUT', 'enum.fade_curve.ease_out'), ('EASE_IN_QUAD', 'enum.fade_curve.ease_in_quad'), ('EASE_OUT_QUAD', 'enum.fade_curve.ease_out_quad'), ('EASE_IN_OUT_QUAD', 'enum.fade_curve.ease_in_out_quad'), ('EASE_OUT_CUBIC', 'enum.fade_curve.ease_out_cubic'), ('EASE_IN_EXPONENTIAL', 'enum.fade_curve.ease_in_exponential'), ('EASE_OUT_EXPONENTIAL', 'enum.fade_curve.ease_out_exponential')], default='DEFAULT', max_length=64),
        ),
    ]
