# Generated by Django 6.0.7 on 2026-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_playlist_fadein_alter_playlist_fadeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English')], default='fr', help_text="Langue de l'utilisateur, détectée automatiquement à la création du compte", max_length=10),
        ),
    ]
