# Generated by Django 6.0.7 on 2026-08-24 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistProposal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REFUSED', 'refused')], default='PENDING', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('duplicated_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_origin', to='main.playlist')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='main.playlist')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_proposals_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_proposals_resolved', to=settings.AUTH_USER_MODEL)),
                ('soundboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_proposals', to='main.soundboard')),
            ],
            options={
                'verbose_name': 'Proposition de playlist',
                'verbose_name_plural': 'Propositions de playlist',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('playlist', 'soundboard'), name='unique_playlist_proposal_per_soundboard')],
            },
        ),
    ]
