# Generated by Django 6.0.7 on 2026-09-03 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_playlistproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundboardScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soundboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='main.soundboard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoundboardScriptStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('PLAY_PLAYLIST', 'PlayPlaylist'), ('STOP_PLAYLIST', 'StopPlaylist'), ('SET_VOLUME', 'SetVolume'), ('PLAY_TRACK', 'PlayTrack')], default='PLAY_PLAYLIST', max_length=50)),
                ('trigger_type', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('TIMECODE', 'Timecode'), ('ON_STEP_END', 'OnStepEnd')], default='IMMEDIATE', max_length=50)),
                ('trigger_offset_ms', models.PositiveIntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.soundboardscript')),
                ('trigger_source_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_steps', to='main.soundboardscriptstep')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
