# Generated by Django 6.1 on 2026-09-11 19:11

from django.db import migrations


def restore_missing_sections(apps, schema_editor):
    SoundBoard = apps.get_model("main", "SoundBoard")
    SoundboardSection = apps.get_model("main", "SoundboardSection")

    for soundboard in SoundBoard.objects.all():
        max_section = (
            SoundboardSection.objects.filter(SoundBoard_id=soundboard.id)
            .order_by("-section")
            .values_list("section", flat=True)
            .first()
        )
        if max_section is None:
            continue

        for section_number in range(1, max_section + 1):
            SoundboardSection.objects.get_or_create(
                SoundBoard_id=soundboard.id,
                section=section_number,
                defaults={
                    "name": f"Section {section_number}",
                    "order": section_number,
                },
            )


def migrate_playlist_soundboard_relation(apps, schema_editor):
    SoundboardPlaylist = apps.get_model("main", "SoundboardPlaylist")
    SoundboardSection = apps.get_model("main", "SoundboardSection")

    for playlist in SoundboardPlaylist.objects.select_related("SoundBoard", "section"):
        if playlist.section_id and playlist.section.SoundBoard_id == playlist.SoundBoard_id:
            continue

        section, _ = SoundboardSection.objects.get_or_create(
            SoundBoard_id=playlist.SoundBoard_id,
            section=1,
            defaults={"name": "Section 1", "order": 1},
        )
        playlist.section_id = section.id
        playlist.save(update_fields=["section"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_soundboardsection'),
    ]

    operations = [
        migrations.RunPython(restore_missing_sections, migrations.RunPython.noop),
        migrations.RunPython(migrate_playlist_soundboard_relation, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='soundboard',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='soundboardplaylist',
            name='SoundBoard',
        ),
    ]
