# Generated by Django 6.1 on 2026-09-11 19:11

from django.db import migrations


def restore_missing_sections(apps, schema_editor):
    sound_board = apps.get_model("main", "SoundBoard")
    soundboard_section = apps.get_model("main", "SoundboardSection")

    for soundboard in sound_board.objects.all():
        max_section = (
            soundboard_section.objects.filter(sound_board_id=soundboard.id)
            .order_by("-section")
            .values_list("section", flat=True)
            .first()
        )
        if max_section is None:
            continue

        for section_number in range(1, max_section + 1):
            soundboard_section.objects.get_or_create(
                sound_board_id=soundboard.id,
                section=section_number,
                defaults={
                    "name": f"Section {section_number}",
                    "order": section_number,
                },
            )


def migrate_playlist_soundboard_relation(apps, schema_editor):
    soundboard_playlist = apps.get_model("main", "SoundboardPlaylist")
    soundboard_section = apps.get_model("main", "SoundboardSection")

    for playlist in soundboard_playlist.objects.select_related("sound_board", "section"):
        if playlist.section_id and playlist.section.sound_board_id == playlist.sound_board_id:
            continue

        section, _ = soundboard_section.objects.get_or_create(
            sound_board_id=playlist.sound_board_id,
            section=1,
            defaults={"name": "Section 1", "order": 1},
        )
        playlist.section_id = section.id
        playlist.save(update_fields=["section_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_soundboardsection'),
    ]

    operations = [
        migrations.RunPython(restore_missing_sections, migrations.RunPython.noop),
        migrations.RunPython(migrate_playlist_soundboard_relation, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='soundboard',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='soundboardplaylist',
            name='SoundBoard',
        ),
    ]
