# Generated by Django 5.1.6 on 2025-08-19 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_alter_playlist_icon_alter_soundboard_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_authenticated', models.BooleanField(default=False, help_text="Indique si l'utilisateur était connecté lors de l'action")),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Date et heure de début de l'action")),
                ('end_date', models.DateTimeField(blank=True, help_text="Date et heure de fin de l'action (pour mesurer la durée)", null=True)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('REGISTRATION', 'registration'), ('SOUNDBOARD_CREATE', 'soundboard_create'), ('SOUNDBOARD_VIEW', 'soundboard_view'), ('SOUNDBOARD_SHARE', 'soundboard_share'), ('PLAYLIST_CREATE', 'playlist_create'), ('PLAYLIST_VIEW', 'playlist_view'), ('PLAYLIST_PLAY', 'playlist_play'), ('MUSIC_UPLOAD', 'music_upload'), ('MUSIC_DELETE', 'music_delete'), ('REPORT_CONTENT', 'report_content'), ('ERROR_404', 'error_404'), ('ERROR_500', 'error_500'), ('ERROR_PERMISSION', 'error_permission')], db_index=True, help_text="Type d'activité effectuée par l'utilisateur", max_length=64)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text="ID de l'entité associée", null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Clé de session pour identifier les utilisateurs non connectés', max_length=40, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur', null=True)),
                ('referrer', models.URLField(blank=True, help_text='URL de référence', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text="Type de l'entité associée (playlist, soundboard, etc.)", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action (null si utilisateur non connecté)", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='main_userac_user_id_386364_idx'), models.Index(fields=['start_date', 'activity_type'], name='main_userac_start_d_71f259_idx'), models.Index(fields=['is_authenticated', 'activity_type'], name='main_userac_is_auth_3bd39b_idx'), models.Index(fields=['session_key', 'start_date'], name='main_userac_session_be0c12_idx'), models.Index(fields=['content_type', 'object_id'], name='main_userac_content_b3fa7c_idx')],
            },
        ),
    ]
