# Generated by Django 4.2.3 on 2025-01-02 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('typePlaylist', models.CharField(choices=[('Instant', 'Son instantanné'), ('Ambient', "Son d'ambiance"), ('Music', 'Musique')], max_length=64)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('colorText', models.CharField(default='#ffffff', max_length=7)),
                ('volume', models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoundBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('colorText', models.CharField(default='#ffffff', max_length=7)),
                ('is_public', models.BooleanField(default=False)),
                ('playlists', models.ManyToManyField(related_name='soundboards', to='home.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=63)),
                ('alternativeName', models.CharField(default=None, max_length=63)),
                ('file', models.FileField(upload_to='musics/')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.playlist')),
            ],
        ),
    ]
