# Generated by Django 5.1.6 on 2025-02-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmationUUID',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
