# Generated by Django 4.2.3 on 2025-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='playlist-playlist/'),
        ),
    ]
