# Generated by Django 5.1.6 on 2025-03-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='useSpecificDelay',
            field=models.BooleanField(default=False),
        ),
    ]
