# Generated by Django 5.1.6 on 2025-03-04 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistColorUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('typePlaylist', models.CharField(choices=[('PLAYLIST_TYPE_INSTANT', 'Son instantanné'), ('PLAYLIST_TYPE_AMBIENT', "Son d'ambiance"), ('PLAYLIST_TYPE_MUSIC', 'Musique')], max_length=64)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('colorText', models.CharField(default='#ffffff', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'typePlaylist')},
            },
        ),
    ]
