# Generated by Django 4.2.3 on 2024-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='typePlaylist',
            field=models.CharField(choices=[('Instant', 'Son instantanné'), ('Ambient', "Son d'ambiance"), ('Musique', 'Musique')], max_length=64),
        ),
    ]
