# Generated by Django 5.1.6 on 2025-03-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_playlist_usespecificdelay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoderationlog',
            name='userOld',
        ),
        migrations.AddField(
            model_name='usermoderationlog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='UserModerationLogUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
