# Generated by Django 5.1.6 on 2025-07-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_linkmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmusic',
            name='domained_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
