# Generated by Django 5.1.6 on 2025-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_confirmationuuid_user_isconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmationUUID',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmationToken',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
