# Generated by Django 4.2.3 on 2025-02-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_isban_user_reasonban'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banExpiration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
