# Generated by Django 4.2.3 on 2025-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_playlist_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboard',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='playlistIcon/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='playlistIcon/'),
        ),
    ]
