# Generated by Django 5.1.6 on 2025-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_playlistcoloruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcoloruser',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
