# Generated by Django 4.2.3 on 2024-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_playlist_soundboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundboard',
            name='colorText',
            field=models.CharField(default='#cafc03', max_length=7),
            preserve_default=False,
        ),
    ]
