# Generated by Django 5.1.6 on 2025-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_linkmusic_domained_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmusic',
            name='urlType',
            field=models.CharField(blank=True, choices=[('FILE', 'file'), ('STREAM', 'stream'), ('OTHER', 'other'), ('ERROR', 'error')], max_length=50),
        ),
    ]
