# Generated by Django 5.1.6 on 2025-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_playlistcoloruser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='useSpecificColor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='typePlaylist',
            field=models.CharField(choices=[('PLAYLIST_TYPE_INSTANT', 'Instant'), ('PLAYLIST_TYPE_AMBIENT', 'Ambient'), ('PLAYLIST_TYPE_MUSIC', 'Music')], max_length=64),
        ),
    ]
