# Generated by Django 4.2.3 on 2024-12-24 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='playlist',
            name='colorText',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='playlist',
            name='volume',
            field=models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='typePlaylist',
            field=models.CharField(choices=[('Instant', 'Son instantanné'), ('Ambient', "Son d'ambiance"), ('Music', 'Musique')], max_length=64),
        ),
        migrations.AlterField(
            model_name='soundboard',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='soundboard',
            name='colorText',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
