# Generated by Django 5.1.6 on 2025-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_confirmationuuid_user_confirmationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmationDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
