# Generated by Django 5.1.6 on 2025-02-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_confirmationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmationDate',
            new_name='demandeConfirmationDate',
        ),
    ]
