# Generated by Django 5.1.6 on 2025-03-06 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_playlist_usespecificcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='maxDelay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
