# Generated by Django 5.1.6 on 2025-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_linkmusic_urltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmusic',
            name='urlType',
            field=models.CharField(blank=True, choices=[('FILE', 'file'), ('STREAM', 'stream'), ('OTHER', 'other'), ('ERROR', 'error')], max_length=50, null=True),
        ),
    ]
