# Generated by Django 5.1.6 on 2025-03-20 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usermoderationlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, choices=[('DARK', 'dark'), ('LIGHT', 'light')], default=None, max_length=50, verbose_name='Theme')),
                ('playlistDim', models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('SoundboardDim', models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserPreference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
