# Generated by Django 5.1.6 on 2025-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_linkmusic_urltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmusic',
            name='urlType',
            field=models.CharField(blank=True, choices=[('FILE', 'file'), ('STREAM', 'stream'), ('OTHER', 'other'), ('ERROR', 'error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='alternativeName',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, choices=[('DARK', 'dark'), ('LIGHT', 'light')], default='light', max_length=50, verbose_name='Theme'),
        ),
    ]
