# Generated by Django 5.1.6 on 2025-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_confirmationdate_user_demandeconfirmationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demandeTokenDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tokenReinitialisation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
