# Generated by Django 5.1.6 on 2025-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_playlist_maxdelay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='soundboard',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uuid',
        ),
    ]
