# Generated by Django 5.1.6 on 2025-03-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Theme'),
        ),
    ]
