# Generated by Django 5.1.6 on 2025-07-25 07:42

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_linkmusic_urltype_alter_track_alternativename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Prénom de l'utilisateur", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isBan',
            field=models.BooleanField(default=False, help_text='Indicates if the user is banned'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isConfirmed',
            field=models.BooleanField(default=False, help_text="Indicates if the user's email is confirmed"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Nom de famille de l'utilisateur", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=encrypted_model_fields.fields.EncryptedCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Nom d'utilisateur (chiffré)", unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, choices=[('dark', 'DARK'), ('light', 'LIGHT')], default='light', max_length=50, verbose_name='Theme'),
        ),
    ]
