# Generated by Django 5.1.6 on 2025-03-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userpreference_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, choices=[('DARK', 'dark'), ('LIGHT', 'light')], default=None, max_length=50, null=True, verbose_name='Theme'),
        ),
    ]
