# Generated by Django 5.1.6 on 2025-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_id_playlist_uuid_rename_id_soundboard_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tempId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soundboard',
            name='tempId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tempId',
            field=models.BigIntegerField(null=True),
        ),
    ]
