# Generated by Django 5.1.6 on 2025-03-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userpreference_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='SoundboardDim',
            new_name='soundboardDim',
        ),
    ]
