# Generated by Django 5.1.6 on 2025-07-25 07:44

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_encrypt_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=encrypted_model_fields.fields.EncryptedCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Nom d'utilisateur", unique=True, verbose_name='username'),
        ),
    ]
