# Generated by Django 5.1.6 on 2025-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_playlist_tempid_soundboard_tempid_user_tempid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tempId',
            field=models.BigIntegerField(default=999, null=True),
        ),
    ]
