# Generated by Django 5.1.6 on 2025-03-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_tempid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tempId',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='soundboard',
            name='tempId',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tempId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
