# Generated by Django 5.1.6 on 2025-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Nom d'utilisateur", max_length=64, unique=True, verbose_name='username'),
        ),
    ]
