# Generated by Django 5.1.6 on 2025-07-28 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTierHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_tier', models.CharField(help_text='Tier précédent', max_length=50)),
                ('new_tier', models.CharField(help_text='Nouveau tier', max_length=50)),
                ('change_reason', models.CharField(choices=[('UPGRADE', 'Upgrade payant'), ('DOWNGRADE', 'Downgrade/Expiration'), ('ADMIN_CHANGE', 'Modification administrative'), ('MIGRATION', 'Migration système'), ('PROMO', 'Promotion/Offre spéciale')], help_text='Raison du changement de tier', max_length=255)),
                ('payment_reference', models.CharField(blank=True, help_text='Référence de paiement associée', max_length=255)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé pour ce changement', max_digits=10, null=True)),
                ('tier_duration_days', models.PositiveIntegerField(blank=True, help_text='Durée du tier en jours', null=True)),
                ('tier_start_date', models.DateTimeField(help_text='Date de début du nouveau tier')),
                ('tier_end_date', models.DateTimeField(blank=True, help_text='Date de fin prévue du tier', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes sur ce changement de tier')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP lors du changement', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent lors du changement')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué le changement (admin/système)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Tier Utilisateur',
                'verbose_name_plural': 'Historiques Tiers Utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='home_userti_user_id_af478a_idx'), models.Index(fields=['change_reason'], name='home_userti_change__818855_idx'), models.Index(fields=['created_at'], name='home_userti_created_919dad_idx')],
            },
        ),
    ]
