# Generated by Django 5.1.6 on 2025-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userfavoritepublicsoundboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, choices=[('DARK', 'dark'), ('LIGHT', 'light')], default=None, max_length=50, verbose_name='Theme'),
        ),
    ]
