# Generated by Django 5.1.6 on 2025-06-06 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userpreference_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeElement', models.CharField(choices=[('playlist', 'playlist'), ('soundboard', 'soundboard')], max_length=25, verbose_name='Type de contenu')),
                ('uuidElement', models.UUIDField(db_index=True)),
                ('precisionElement', models.CharField(choices=[('unknown', 'unknown'), ('image', 'image'), ('text', 'text'), ('music', 'music')], max_length=25, verbose_name="precision sur l'élément")),
                ('descriptionElement', models.TextField(verbose_name="Description de l'élément")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resultModerator', models.CharField(choices=[('playlist', 'playlist'), ('soundboard', 'soundboard')], max_length=25, verbose_name='Type de contenu')),
                ('dateResultModerator', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
