# Generated by Django 5.1.6 on 2025-06-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_reportcontent_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
