# Generated by Django 5.1.6 on 2025-06-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_reportcontent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='dateResultModerator',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de la modération'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_reports', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='resultModerator',
            field=models.CharField(choices=[('invalid', 'invalid'), ('valid', 'valid'), ('spam', 'spam'), ('duplicate', 'duplicate'), ('other', 'other')], max_length=25, verbose_name='Resultat moderateur'),
        ),
    ]
