# Generated by Django 5.1.6 on 2025-06-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_reportcontent_dateresultmoderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='resultModerator',
            field=models.CharField(choices=[('invalid', 'invalid'), ('valid', 'valid'), ('spam', 'spam'), ('duplicate', 'duplicate'), ('other', 'other'), ('copyright', 'copyright')], max_length=25, verbose_name='Resultat moderateur'),
        ),
    ]
