# Generated by Django 5.1.6 on 2025-06-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_reportcontent_resultmoderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoderationlog',
            name='model',
            field=models.CharField(choices=[('unknown', 'unknown'), ('playlist', 'playlist'), ('soundboard', 'soundboard'), ('user', 'user')], default='unknown', max_length=50, verbose_name="Model de d'origine de l'avertissement"),
        ),
        migrations.AddField(
            model_name='usermoderationlog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModerationLogReport', to='home.reportcontent'),
        ),
    ]
