# Generated by Django 5.1.6 on 2025-06-12 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_reportcontent_precisionelement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoderationlog',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModerationLogModerator', to=settings.AUTH_USER_MODEL),
        ),
    ]
