# Generated by Django 5.1.6 on 2025-06-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_usermoderationlog_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reasonBan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermoderationlog',
            name='model',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('PLAYLIST', 'PLAYLIST'), ('SOUNDBOARD', 'SOUNDBOARD'), ('USER', 'USER')], default='unknown', max_length=50, verbose_name="Model de d'origine de l'avertissement"),
        ),
    ]
