# Generated by Django 5.1.6 on 2025-06-23 14:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_music_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSoundboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('soundboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='home.soundboard')),
            ],
        ),
    ]
