# Generated by Django 5.1.6 on 2025-07-02 12:07

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_music_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nom du tag (3-50 caractères)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du tag', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le tag est actif et peut être utilisé')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='soundboard',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associés à ce soundboard', related_name='soundboards', to='home.tag'),
        ),
    ]
