# Generated by Django 5.1.6 on 2025-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_tag_soundboard_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='betaTester',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a beta tester'),
        ),
    ]
