# Generated by Django 5.1.6 on 2025-07-07 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_user_betatester'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_name', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM_BASIC', 'Premium Basic'), ('PREMIUM_PRO', 'Premium Pro'), ('PREMIUM_ENTERPRISE', 'Premium Enterprise')], default='STANDARD', help_text="Tier actuel de l'utilisateur", max_length=50)),
                ('previous_tier', models.CharField(blank=True, help_text='Tier précédent avant le changement', max_length=50, null=True)),
                ('tier_start_date', models.DateTimeField(auto_now_add=True, help_text='Date de début du tier actuel')),
                ('tier_expiry_date', models.DateTimeField(blank=True, help_text="Date d'expiration du tier (pour les abonnements premium)", null=True)),
                ('subscription_active', models.BooleanField(default=False, help_text="Indique si l'abonnement est actif")),
                ('auto_renew', models.BooleanField(default=False, help_text="Renouvellement automatique de l'abonnement")),
                ('custom_soundboard_limit', models.PositiveIntegerField(blank=True, help_text='Limite personnalisée de soundboards (surcharge le tier)', null=True)),
                ('custom_playlist_limit', models.PositiveIntegerField(blank=True, help_text='Limite personnalisée de playlists (surcharge le tier)', null=True)),
                ('custom_music_per_playlist_limit', models.PositiveIntegerField(blank=True, help_text='Limite personnalisée de musiques par playlist (surcharge le tier)', null=True)),
                ('custom_weight_music_limit', models.PositiveIntegerField(blank=True, help_text='Limite personnalisée de poids de musique en MB (surcharge le tier)', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Référence de paiement ou ID de transaction', max_length=255)),
                ('notes', models.TextField(blank=True, help_text="Notes administratives sur le tier de l'utilisateur")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tier Utilisateur',
                'verbose_name_plural': 'Tiers Utilisateurs',
                'ordering': ['-tier_start_date'],
            },
        ),
    ]
