# Generated by Django 5.1.6 on 2025-07-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_usertier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertier',
            name='custom_music_per_playlist_limit',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='custom_playlist_limit',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='custom_soundboard_limit',
        ),
        migrations.RemoveField(
            model_name='usertier',
            name='custom_weight_music_limit',
        ),
        migrations.AlterField(
            model_name='usertier',
            name='previous_tier',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('PREMIUM_BASIC', 'Premium Basic'), ('PREMIUM_PRO', 'Premium Pro'), ('PREMIUM_ENTERPRISE', 'Premium Enterprise')], help_text='Tier précédent avant le changement', max_length=50, null=True),
        ),
    ]
