# Generated by Django 5.1.6 on 2025-07-07 12:01

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_usertier_custom_music_per_playlist_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertier',
            name='payment_reference',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Référence de paiement ou ID de transaction'),
        ),
    ]
