# Generated by Django 5.1.6 on 2025-07-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_usertier_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertier',
            name='subscription_active',
        ),
    ]
