# Generated by Django 5.1.6 on 2025-07-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_usertier_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertier',
            name='previous_tier',
        ),
    ]
