# Generated by Django 5.1.6 on 2025-07-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_usertier_previous_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Domain',
                'verbose_name_plural': 'Blacklisted Domains',
            },
        ),
        migrations.AlterField(
            model_name='usertier',
            name='tier_name',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM_BASIC', 'Premium Basic'), ('PREMIUM_ADVANCED', 'Premium Advanced'), ('PREMIUM_PRO', 'Premium Pro')], default='STANDARD', help_text="Tier actuel de l'utilisateur", max_length=50),
        ),
    ]
