name: git-gardian
run-name: ${{ github.actor }} is starting a security scan and build
on: [push, workflow_dispatch]

jobs:
  secret-scan:
    name: GitGuardian Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.30.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}