name: git-gardian
run-name: ${{ github.actor }} is starting a build 🚀
on: [push, workflow_dispatch]
jobs:
  Git-Gardian:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build ${{ github.ref }} started."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: docker --version
      - name: init .env file
        run: |
          cp .env.CI .env
      - name: Build and run Docker Compose
        run: |
          docker compose up -d --build
      