name: CD-test
run-name: CD-test | ${{ github.ref }} | ${{ github.actor }}
on:
  - push

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildDockerCompose:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - run: echo "Build ${{ github.ref }} started."

      - name: Check out repository code
        uses: actions/checkout@v6

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: docker --version

      - name: init .env file
        # TODO : remove this line when the CI environment variables are moved to GitHub secrets
        run: cp .env.CI .env

      - name: Build and run Docker Compose
        run: docker compose -f docker-compose.prod.yml up --build -d

      - name: Check containers are healthy
        run: |
          sleep 10
          docker compose -f docker-compose.prod.yml ps --status running | grep -q "Up" || (docker compose -f docker-compose.prod.yml logs && exit 1)

  # CreateVersionBranch:
  #   needs: BuildDockerCompose
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: read
  #     contents: write
  #   outputs:
  #     new_version: ${{ steps.bump_version.outputs.new_version }}
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v6
  #       with:
  #         fetch-depth: 0

  #     - name: Determine current version and bump minor
  #       id: bump_version
  #       run: |
  #         git fetch --tags
  #         latest_tag=$(git tag -l | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)

  #         if [ -z "$latest_tag" ]; then
  #           latest_tag="0.0.0"
  #         fi

  #         IFS='.' read -r major minor patch <<< "$latest_tag"
  #         new_patch=$((patch + 1))
  #         new_version="${major}.${minor}.${new_patch}"

  #         echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

  #     - name: Create and push new branch
  #       run: |
  #         git config user.name "github-actions[bot]"
  #         git config user.email "github-actions[bot]@users.noreply.github.com"
  #         git checkout -b "${{ steps.bump_version.outputs.new_version }}"
  #         git push origin "${{ steps.bump_version.outputs.new_version }}"

  TriggerDockerDigestUpdate:
    needs: BuildDockerCompose
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger downstream workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "Docker-digest-update.yml" \
            --repo ${{ github.repository }} \
            --ref 0.4.8 \
            --branch ${{ github.ref }}
